import type { Metadata } from "next";
import "../components/header.tsx";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body>
        <header></header>
        {children}
      </body>
    </html>
  );
}
